title: FJ
email: "jiang.tf.2020@gmail.com"
linkedin: "https://www.linkedin.com/in/freddy-jiang-a949331a3/"
github: "https://github.com/j-freddy"
itch: "https://litetj.itch.io/"
scratch: "https://scratch.mit.edu/users/Relfirm/"